from enum import Enum

class State(Enum):
    INPUT_NAMA = "INPUT_NAMA"
    INPUT_NAMA_WARUNG = "INPUT_NAMA_WARUNG"
    INPUT_WILAYAH_WARUNG = "INPUT_WILAYAH_WARUNG"
    INPUT_LOKASI_WARUNG = "INPUT_LOKASI_WARUNG"
    TIPE_WARUNG = "TIPE_WARUNG"
    MENU = "MENU"
    INPUT_STOK = "INPUT_STOK"